name: Schedule Test

on:
  workflow_dispatch:
  schedule:
    - cron: "2,12,22,32,42,52 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Show scheduler time
        run: |
          echo "GitHub schedule triggered successfully"
          echo "UTC:"
          date -u
          echo "IST:"
          TZ=Asia/Kolkata date
